---

- hosts: all
  become: true
  tasks:

   - name: update repository index
     apt:
      update_cache: yes
   - name: install apache2
     apt:
      name: apache2
      state: absent
   - name: add php support for apache
     apt:
      name: libapach2-mod-php
      state: absent	  	  
