---

- hosts: all
  become: yes
  pre_tasks:

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution ==  "CentOS"
  - name: install update (Ubuntu)
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution ==  "Ubuntu"

- hosts: all
  become: true
  tasks:
  - name: create simon user 
    tags: always
    user:
      name: simon
      groups: root
  - name: add sh key for simon
    tags: always
    authorized_key:
      user: simon
      key: "ssh_code"

  - name: add sudoers file for simon
    tags: always
    copy: 
      src: sudoer_simon
      dest: /etc/sudoers.d/simon
      owner: root
      group: root
      mode: 0440    
- hosts: workstations
  become: true
  tasks:
  - name: install unzip
   package: 
     name: unzip
  
  - name: install terraform
   unarchive:
     src: https://sdsdsdsssds/terraform.zip    
     dest: /usr/local/bin
     remote_src: yes
     mode: 0775
     owner: root
     group: root


- hosts: Web_server
  become: true
  tasks:

  - name: install apache and  php for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and  php for CentOs
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes  
    when: ansible_distribution  == "CentOS" 
  - name: restart httpd (CenOS)
    tags: apache,centos,httpd
    service:  
      name: httpd
      state: restarted
    when: httpd.changed    
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      desc: /var/www/html/index.html
      owner: root
      group: root
      mode:0644

- hosts: DB_Server
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"
   
  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 
      
- hosts: File_Server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

