---
- hosts: all
  become: true
  tasks:

# tasks file for oracle-database
- name: install oracle database
  tasks: 
  - include_tasks: install-db.yml
  become: yes
  become_user: root
  tags:
    - install_database

- name: create listener oracle database 11g
  tasks:
   - include_tasks: create-listener.yml
  become: yes
  become_user: oracle
  tags:
    - create_listener

- name: configure instance oracle database 11g
  tasks: 
   - include_tasks: create-instance.yml
  become: yes
  become_user: oracle
  tags:
    - create_instance
